apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector: 
   project: Replication 
   service: web
   version: "0.1"
  template:
   metadata:
    name: nginx
    lables: 
     project: Replication
     service: web
     version: "0.1"
  spec:             
    containers: 
   - name: nginx
     image: nginx
     ports:
    - containerPort: 80 