apiVersion: apps/v1betal
kind: Deployment
metadata:
	name: tomcat
spec:
	replicas: 1
    template:
		metadata:
			labels:
				run: tomcat
		spec:
          containers:
             - image: tomcat 
               name: tomcat 
               ports:
               - containerPort: 8080
			   volumeMounts:
               - mountPath: /usr/local/tomcat/logs
               name: tomcat-log
          volumes: 
          - name: tomcat-log
          gcePersistentDisk:
             pdname: gce-pd-1
             fsType: ext4			 